# Generated by Django 5.1.6 on 2025-02-16 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='Courses/Category/images')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('poster', models.ImageField(blank=True, null=True, upload_to='Courses/poster/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='Courses/banner/')),
                ('introduction', models.FileField(blank=True, null=True, upload_to='Courses/intro/')),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('INP', 'In Progress'), ('COM', 'Completed')], default='INP', max_length=3)),
                ('pricing_status', models.CharField(choices=[('Fr', 'Free'), ('Pr', 'Purchasable')], default='Pr', max_length=2)),
                ('price', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course_Category', to='Courses.category')),
                ('students', models.ManyToManyField(blank=True, related_name='User_Courses', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Techer_Courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
