# Generated by Django 5.1.6 on 2025-02-16 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaqCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Faq_Course', to='Courses.course')),
            ],
            options={
                'verbose_name': 'FAQ Course',
                'verbose_name_plural': 'FAQs Courses',
            },
        ),
    ]
